- docker-alfresco/Dockerfile
- war/src/main/webapp/error.jsp
Unpack root.war
Grant alfresco all security permissions
Grant root.war only permission to deploy
> REPO-3275 secure tomcat

- pom.xml
- updated sync service module to 3.0
> APPSREPO-486 : Release Sync Service 3.0

- pom.xml
- increase MM version from 1.2.0 to 1.2.1
> MM-729 : Generate Final Build for Media Management 1.2.1 with Publishing

- docker-alfresco/pom.xml
- pom.xml
- war/src/main/webapp/index.jsp
Add alfresco-api-explorer version property to pom.xml
Add alfresco-api-explorer dependency to docker-alfresco/pom.xml and unpack it using maven-dependency-plugin
Marked "Alfresco WebScripts - Home" as internal
Add url api-explorer to index.jsp
> REPO-3539 : Integrate Api-Explorer

- README.md
- docker-alfresco/aws/pom.xml
- make profile enterpriseDocker working for building the aws image locally
> REPO-3829 aws image

- docker-alfresco/test/docker-alfresco-all-amps-test/pom.xml
- pom.xml
- updated to newly released version
> MM-763 : Renditions: Release MM 1.3.0-RC1 for ACS 6.1

- pom.xml
> [ MNT-19577 ] Updated alfresco-data-model version (8.18 -> 8.19)

- pom.xml
- updated to latest MM 1.3.0-RC4 release
- build: https://bamboo.alfresco.com/bamboo/browse/PLAT-ACS151 is green now
> MM-772 : Release MM 1.3.0-RC4 (for ACS 6.1 RC1 on OpenJDK 11)

- docker-alfresco/Dockerfile
- docker-alfresco/aws/pom.xml
- docker-alfresco/pom.xml
> REPO-3943 vti bin

- pom.xml
* increment alfresco root version
> REPO-4091 Bring in ACS with updated root war.

- docker-alfresco/test/docker-alfresco-all-amps-test/pom.xml
- pom.xml
Updated S3 connector version to 2.3.0 and added Glacier Connector dependency
> RM-6679 Integration with Glacier Connector 1.0.0-EA1

- docker-alfresco/test/cluster-test/docker-compose.yml
Change the level of log on PostgresImage.
> REPO-3942 : PostgreSQL image logs errors 

- docker-alfresco/Dockerfile
- docker-alfresco/pom.xml
This PR moves unpacking of ROOT and _vti_bin to maven and removes unnecessary steps from dockerfile.
> Simplify dockerfile

- pom.xml
alfresco-repository 7.43
alfresco-remote-api 7.35
> Update dependencies (library upgrades)

- pom.xml
This needs to be merged up to 6.1.0
> Update supported Outlook version 2.5.1

- pom.xml
> REPO-4132: User 'System' cleanup follow-up

- pom.xml
Updated components with versions from SP branches.
> REPO-4132: System user follow-up

- pom.xml
Use alfresco-repository 7.33.13 and alfresco-remote-api 7.34.2.
> SEARCH-1354 Update versions.

- pom.xml
Use alfresco-repository 6.56.13 and alfresco-remote-api 6.39.5.
> SEARCH-1354 Update internal versions.

- pom.xml
Use alfresco-repository 6.56.13 and alfresco-remote-api 6.39.5.
(cherry picked from commit c52ac00c98f4309231753a8be77ad063d5c2a966)
> SEARCH-1354 Update internal versions. (#178)

- pom.xml
> MM-765 : MM 1.3.0 release for ACS 6.1

- CHANGELOG.md
- pom.xml
Update change notes. Added 6.2.0 section
> REPO-3276 EOL: Remove DB2

- war/src/main/webapp/WEB-INF/web.xml
* add missing cors.supportedHeaders range
* cors.exposedHeaders
> REPO-4217 Add missing core configuration

- pom.xml
Updated alfresco-repository dependency version.
> [SEARCH-1272] updated repository depdendency version.

- CHANGELOG.md
- pom.xml
> REPO-4226 : jackson upgrade

- docker-alfresco/aws/pom.xml
- docker-alfresco/test/docker-alfresco-all-amps-test/pom.xml
- pom.xml
- added ai repo amp dependency
Build is green: https://bamboo.alfresco.com/bamboo/browse/PLAT-ACS291-AAV-2
> ATS-292 : AI-CE: Repo AI Ext - packaging & deployment into AWS

- distribution/src/main/resources/VERSIONS.md
- pom.xml
> ATS-355 : AI-CE: Internal Release 0.4 (with zip delta distribution)

- distribution/src/main/resources/VERSIONS.md
- pom.xml
Once merged, this change will be cherry-picked into:
* **support/SP/6.1.N**
* **master**
> ATS-380 : Update AI amp version to 1.0.0

- distribution/src/main/resources/VERSIONS.md
To be merged after official / company release of IE 1.1.0.1
> Search-1499: Updated versions.md with the Insight Engine version 1.1.0.1

- docker-alfresco/test/docker-compose.yml
- pom.xml
- war/src/main/webapp/WEB-INF/web.xml
* adjust web.xml for cors context listener
> REPO-4219 create CORS context listener

- docker-alfresco/test/docker-prometheus/docker-compose.yml
- docker-alfresco/test/docker-prometheus/prometheus.yml
- docs/micrometer/README.md
REPO-4381 : added docker-compose for prometheus and grafana.  For test use only.
> REPO-4381 : added docker-compose for prometheus and grafana. 

- pom.xml
updated alfresco-remote-api dependency version
> [MNT-20507]

- pom.xml
Bump spring version to 5.1.8.RELEASE
> Merge fix/REPO-4505_update_spring into support/SP/6.0.N

- pom.xml
Bump spring version to 5.1.8.RELEASE
> Merge fix/REPO-4505_upgrade_spring_61N into support/SP/6.1.N

- pom.xml
@aborroy the PR contains the required dependencies versions related with those branches you already reviewed.
> [ SEARCH-1609 ] enterprise-repository and enterprise-remote-api deps version updated

- docker-alfresco/test/docker-alfresco-all-amps-test/pom.xml
- pom.xml
Reverts Alfresco/acs-packaging#329
> Revert "REPO-4503: Upgrade hazelcast 3.11.2 on 6.1.N"

- pom.xml
Update cxf libraries to 3.3.2
Update alfresco libraries
> REPO-4504 upgrade cxf-rt-transports-http 6.1

- docker-alfresco/test/docker-alfresco-all-amps-test/pom.xml
- docker-alfresco/test/docker-alfresco-all-amps-test/test/docker-compose.yml
- pom.xml
> REPO-4461 Support old style Hazelcast config

- pom.xml
- merge to master and cherry-pick to support/SP/6.1.N (ready for ACS 6.1.1 - including AWS variant of Repo docker image)
> ATS-462: Update ACS packaging with AIS 1.0.2

- pom.xml
update alfresco-repository dependency version
> [SEARCH-1746]

- docs/custom-transforms-and-renditions.md
Alan's contributions: Like the basic structure and wording. Trying to tighten it up a bit.
Still a WIP, but I will keep going through the doc.
> WIP: Feature/repo 4338 helloworld alan

- docker-alfresco/Dockerfile
- pom.xml
- pick up latest upstream projects
> REPO-4329 Custom Renditions

- pom.xml
- Bump to SAML 1.2.0-RC1 version in the pom.xml file
> REPO-4621: Fix SAML share PO tests and release

- docker-alfresco/test/docker-alfresco-all-amps-test/pom.xml
- pom.xml
- see corresponding release of alfresco-repository.jar (7.xx)
- https://github.com/Alfresco/alfresco-repository/pull/582
> WIP: MM-820: Update to Gytheio 0.10.x (=> 0.10.1)

- pom.xml
Updated alfresco-repository and enterprise-repository dependency versions.
> [SEARCH-1829]

- pom.xml
> MM-786: Bump to MM 1.4.0-RC3 (targeting ACS 6.2.0 RCs)

- docs/creating-a-t-engine.md
- docs/custom-transforms-and-renditions.md
- docs/migrating-a-legacy-transformer.md
Add Legacy transformer transformOption and Pipeline config.
> Complete Migrating a Legacy Transformer Documentation.

- docker-alfresco/test/docker-alfresco-all-amps-test/pom.xml
- pom.xml
> REPO-4628 [ACS 6.2. Compatibility] S3 Connector - update to version 3.0-RC3

- docker-alfresco/test/cluster-test/docker-compose.yml
- docker-alfresco/test/docker-compose.yml
Added share URL to CORS allowed origins.
> REPO-4676 : Create site dialog is not closed after completing the form

- docker-alfresco/test/docker-alfresco-all-amps-test/pom.xml
- pom.xml
Bump Glacier connector version to 2.0.0-RC1
> Bump version of glacier connector.

- pom.xml
(cherry picked from commit f14c2df47a03eafb63220aba2882b9339f6b5bb0)
> Bump jackson-databind to version 2.9.10 (#477)

- pom.xml
(cherry picked from commit 07a2f570d59e3f8cbda7882c2b56cf2e42cb556d)
> Bump jackson-databind to version 2.9.10

- docs/create-custom-image-using-existing-docker-image.md
Shows how we do proceed if one liked to add an amp to a custom image based on repository content image.
Switching between Root and alfresco users, root for adding new files, alfresco for the run.
> REPO-4648: Update doc Dockerfile

- docs/custom-transforms-and-renditions.md
- add link to ATS docs for configuring a custom Engine
> ATS-520 : ATS: Review Draft Docs for Alfresco Transform Service (ATS) 1.1

- pom.xml
- includes fix for MM-827 (fix MM Share AMP for Video Trim.& Image Crop)
> MM-828: Update ACS packaging version of MM from 1.4.0-RC3 to 1.4.0-RC5

- pom.xml
Once this PR is merged we'll also cherry-pick the commit into the `support/SP/6.2.N` branch.
> ATS-571: Release Intelligence Services (AIS) 1.1.0-RC3

- pom.xml
Once reviewed & merged, this commit will  be cherry-picked into the **support/SP/6.2.N** branch.
> ATS-516: Release Intelligence Services (AIS) 1.1.0

- pom.xml
Upgrade alfresco-remote-api dependency
> REPO-4663: Update pom.xml alfresco-remote-api version

- pom.xml
> ATS-612 : AI-CE: Release Intelligence Services (AIS) 1.1.1-RC1

- pom.xml
> ATS-613 : AI-CE: "Engineering Release" of AIS 1.1.1 (for ACS 6.2.x)

- pom.xml
Bump enterprise-remote-api to 8.56
Bump enterprise-repository to 8.60
Bump remote-api to 8.73
Bump repository to 8.61
Bump data-model to 8.75
Bump core to 8.12
Bump api-explorer to 6.2.1
> REPO-4917 : Pick upsteam projects

- pom.xml
- upgrade gytheio
- remove commons-lang
> MM-841 : Remove old commons-lang lib from Gytheio

- .travis.yml
- pom.xml
- tests/scripts/wait-for-alfresco-start.sh
- war/src/main/webapp/WEB-INF/web.xml
Cherry-picked from:
https://github.com/Alfresco/acs-packaging/commit/fc686b5465679b6490f34f13f0214fa2c1abce34
Tested on 6.0.N via API request script.
Subject to approval of https://github.com/Alfresco/alfresco-remote-api/pull/533
> MNT-21070: InMemoryTicketComponentImpl_leaks_currentTicket_information_from_one_request_to_another

- pom.xml
- war/src/main/resources/log4j.properties
Add alternative script into log4j setting in order to be changed by support tools.
(cherry picked from commit 6ef1d6bc2beb84ca481b5e6f31082ab833665fb7)
> MNT-21083: Alternative clean up script

- pom.xml
Bump jackson-databind to 2.9.10.3
Pick upstream projects
> MNT-21358 : Jackson Databind lacks certain xbean-reflect

- pom.xml
> ATS-651 : AIS: Release Intelligence Services 1.1.2 

- pom.xml
> SHA-2445 : share-services amp (6.2.1) packs repo components

- CHANGELOG.md
- pom.xml
Bump Share version to 6.1.0.3
Bump AOS version to 1.2.2.1
> MNT-21394 : Prepare 6.1.0.8 release

- pom.xml
updated alfresco-enterprise-repository version
> [SEARCH-2098]

- docker-alfresco/Dockerfile
* Change DOCKERFILE USERNAME variable to IMAGEUSERNAME to not clash with Windows USERNAME
> REPO-5037: Fix f8 maven plugin on Windows

- .travis.yml
- distribution/pom.xml
- docker-alfresco/aws/pom.xml
- docker-alfresco/pom.xml
- docker-alfresco/test/docker-alfresco-all-amps-test/pom.xml
- pom.xml
- tests/pom.xml
- tests/tas-all-amps/pom.xml
- tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
- tests/tas-cluster/pom.xml
- tests/tas-cmis/pom.xml
- tests/tas-email/pom.xml
- tests/tas-integration/pom.xml
- tests/tas-restapi/pom.xml
- tests/tas-sync-service/pom.xml
- tests/tas-webdav/pom.xml
- war/pom.xml
- change version to 7.0
- comment all the amps that have the max repo version < 7.0
- changes required on amps will be done in https://issues.alfresco.com/jira/browse/REPO-5086
> REPO-5072: Update version of acs-packaging to 7.0

- tests/scripts/wait-for-alfresco-start.sh
- fix by setting the proper container name
> Fix adding logs in case alfresco is not starting

- .travis.yml
- scripts/veracode/static_analysis.sh
- add retry on failed veracode scan attempts
- wait between retries
> ACS-102 : Veracode build instability in acs-packaging

- pom.xml
- tests/tas-all-amps/pom.xml
- tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
- see also APPS-119, APPS-102 (ACS-205), APPS-121
- TODO once green and merged to 6.2.N also cherry-pick to master
> APPS-122: Update MM from 1.4.0 to 1.4.1-RC3 (for ACS 6.2.1)

- pom.xml
-Create Site fails with Kerb SSO in 6.2
> [MNT-21363][MNT-21511] Updated alfresco-remote-api version from 7.134 to 7.135

- pom.xml
- tests/tas-all-amps/pom.xml
- tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
- updated glacier to new 2.1.0-A2 released version
- enabled the tests
> REPO-5165 : Glacier Connector: review compatibility for ACS 6.2.1 and MM 1.4.1

- pom.xml
> [SEARCH-2279]

- tests/environment/docker-compose-aims.yml
- tests/environment/docker-compose-all-amps-test.yml
- tests/environment/docker-compose-cluster.yml
- tests/environment/docker-compose-cmis-tests.yml
- tests/environment/docker-compose-email-tests.yml
- tests/environment/docker-compose-integration-tests.yml
- tests/environment/docker-compose-minimal.yml
- tests/environment/docker-compose-node-restart.yml
- tests/environment/docker-compose-rest-api-tests.yml
- tests/environment/docker-compose-sync-service.yml
- tests/environment/docker-compose-with-ldap.yml
When using the JAVA_TOOL_OPTIONS environment variable, values are not passed as command line arguments to the Java Process
> SEARCH-1915 Use hidden variable for config

- pom.xml
- acs-packaging PR for Share 6.2.2-RC2
> APPS-203 : Create Share 6.2.2-RC2

- pom.xml
- note: requires ATS (T-Router) 1.3.0-RC1 (or higher)
> ATS-786: Bump to AIS 1.2.0-RC1

- pom.xml
- bump saml version to 1.2.1-RC1
> ACS-366: SAML 1.2.1 Release Candidate

- pom.xml
> ACS-367: SAML 1.2.1 Final Release

- pom.xml
- acs-packaging PR for Share 6.2.2 release
> APPS-229 : Create Share 6.2.2 Final Build

- pom.xml
- update MM version from 1.4.2-RC1 to 1.4.2
> ACS-381: MM 1.4.2 release

- pom.xml
> MNT-21619 : downgrade maven sourceVersion to 1.8 for JDK8 compatibility

- pom.xml
- tests/tas-restapi/src/test/java/org/alfresco/rest/sites/members/GetSiteMemberTests.java
- tests/tas-restapi/src/test/java/org/alfresco/rest/sites/members/GetSiteMembersTests.java
https://issues.alfresco.com/jira/browse/REPO-5184
> Bump repo and remote api versions

- .travis.yml
- docker-alfresco/Dockerfile
- pom.xml
- tests/environment/docker-compose-aims.yml
- tests/environment/docker-compose-all-amps-test.yml
- tests/environment/docker-compose-cluster.yml
- tests/environment/docker-compose-cmis-tests.yml
- tests/environment/docker-compose-email-tests.yml
- tests/environment/docker-compose-integration-tests.yml
- tests/environment/docker-compose-minimal.yml
- tests/environment/docker-compose-node-restart.yml
- tests/environment/docker-compose-rest-api-tests.yml
- tests/environment/docker-compose-sync-service.yml
- tests/environment/docker-compose-with-ldap.yml
Cherry-picked from #999 #1229 and #1331
> MNT-21731 SEARCH-1915: Keystore Metadata config

- .travis.yml
- docker-alfresco/Dockerfile
- pom.xml
- tests/environment/docker-compose-aims.yml
- tests/environment/docker-compose-all-amps-test.yml
- tests/environment/docker-compose-cluster.yml
- tests/environment/docker-compose-cmis-tests.yml
- tests/environment/docker-compose-email-tests.yml
- tests/environment/docker-compose-integration-tests.yml
- tests/environment/docker-compose-minimal.yml
- tests/environment/docker-compose-node-restart.yml
- tests/environment/docker-compose-rest-api-tests.yml
- tests/environment/docker-compose-sync-service.yml
- tests/environment/docker-compose-with-ldap.yml
Cherry picked commit : 93a0fa74a40452a71dbbc8ae351af79ed931ad89
> MNT-21731 : CLONE - Sensitive data hard-coded in configuration files

- tests/environment/docker-compose-pipeline-all-amps.yml
Contains update to base java image 11.0.7-openjdk-centos-7-dcd8edf6cb70
> ATS-814 Update SFS to 0.10.0

- pom.xml
> APPS-314 : Verify release stage from Share Build

- pom.xml
- tests/environment/docker-compose-all-amps-test.yml
- tests/tas-all-amps/Dockerfile
- tests/tas-all-amps/pom.xml
- tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
- bump S3Connector to 3.1.0-RC2
> ACS-512: S3 Connector 3.1.0 Release Candidate

- pom.xml
- tests/environment/docker-compose-all-amps-test.yml
- tests/tas-all-amps/pom.xml
- tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
- cherry-pick 70364a2b42e45f2cedf2426dbe92fdd18e0431bf from 6.2.N
> ACS-512: S3 Connector 3.1.0 Release Candidate (2)

- pom.xml
- tests/pipeline-all-amps/repo/pom.xml
- tests/tas-all-amps/pom.xml
- tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
> ACS-514: Check compatibility with Glacier version 2.1.0-RC1, S3 Connector version 3.1.0-RC3

- pom.xml
> ACS-580 : Direct access urls - revert initial api version

- pom.xml
> APPS-476 : SHARE - Release of 7.0.0-Mx version

- pom.xml
- bump s3connector version to 3.1.0
> ACS-644: S3 Connector 3.1.0 Final Release

- pom.xml
> APPS-541: [AOS] Upgrade for ACS 7 compatibility

- pom.xml
bump of Salesforce connector to 2.2.0
bump of mediaManagement to 1.4.3.1
bump of AOS to 1.3.2-RC1
All this bumps got tested already separately but their respective PR got stuck. So i take them back in order to clean up and make the bumps
> APPS-860 update dependencies

- pom.xml
> MNT-21871 : [Security] Multiple jackson-databind vulnerabilities

- .travis.yml
- pom.xml
Upgrade of Share and Share Services Amp to the latest released version
> APPS-553: Share version 7.0.0-M2 doesn't display the correct version

- pom.xml
- PR in acs-packaging for Share 7.0.0-A6
> APPS-595 : Changes from MNT-20195 break Travis build for alfresco-community-repo

- pom.xml
> ACS-741 : SAML - Logout is not working on Chrome

- pom.xml
> MNT-18497 : Displaying Folder With Many Linked Nodes is Slow in Share

- pom.xml
this version include a revert for webscripts useful for AGS to move over tests.
> bumpo of share to A13

- pom.xml
> ACS-1016 : Azure Connector 1.2.0 Final Release

- .travis.yml
- tests/pipeline-all-amps/pom.xml
- tests/pipeline-all-amps/repo/pom.xml
- tests/pipeline-all-amps/share/pom.xml
Use explicit maven configuration for fabric8-maven-plugin rather than command line properties
> ACS-1077 fix pipeline image tag

- dev/dev-tomcat/src/main/tomcat/shared/classes/alfresco-global.properties
- dev/dev-tomcat/src/main/tomcat/shared/classes/alfresco/extension/custom-log4j.properties
- docs/query-accelerator.md
- pom.xml
Now using: queryAccelerator.config.dir=shared/classes/alfresco/extension/queryaccelerator
> REPO-5534 Make Query Accelerator config directory setup consistent

- pom.xml
Updated the REST API Explorer to the latest version, upgraded to Swagger UI 3: https://github.com/Alfresco/rest-api-explorer/releases
> Updated the API Explorer to the latest version

- docs/query-accelerator.md
> [REPO-5543] Query Accelerator documentation update in regards to logging

- docs/query-accelerator.md
Very minor changes, most of it was already there.
> Fixed query set example, introduced brief explanation

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchTests.java
Because values for milliseconds-since-the-epoch and seconds-since-the-epoch must be non-negative we have to test what happens when we use a negative epoch when we create a node.
This PR should be green when https://github.com/Alfresco/acs-event-model/pull/12 will be merged.
> SEARCH-2707 add a test to verify that the system is able to index and search for dates before 1970

- pom.xml
- updated azure connector to 2.0-A3
> ACS-1312: Azure Connector 2.0: Classpath conflict

- distribution/src/main/resources/VERSIONS.md
> Update of Supported Office Versions

- pom.xml
> ACS-1233: Azure Connector 2.0.0 Final Release

- .travis.yml
- tests/pipeline-all-amps/repo/dtas/dtas-config.json
Also updated config file to use module id instead of name/title and removed hardcoded AGS version.
> OPSEXP-809: Upgrade DTAS to 1.0.1

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchTests.java
Depends on https://github.com/Alfresco/alfresco-tas-restapi/pull/126
> SEARCH-2748 test include parameter

- pom.xml
- update S3 Connector's version
> ACS-1489 : S3 Connector 3.1.0.2

- pom.xml
- update s3connector and azureconnector dependecies
> ACS-1488 / ACS-1490: S3Connector 4.0.0.1 and AzureConnector 2.0.0.1 HF releases

- .travis.yml
- tests/pipeline-all-amps/repo/Dockerfile
- tests/pipeline-all-amps/repo/pom.xml
See OPSEXP-841
Notes on AGS api explorer:
DTAS has the API exporer for AGS  use the /gs-api-explorer context (as per guidance from the AGS team) so the pipeline-all-amps has been changed to reflect that
> OPSEXP-841 upgrade to DTAS 1.1

- pom.xml
- bump saml version to 1.2.2-A1
> ACS-1578: Release SAML module 1.2.2-A1

- pom.xml
Updated share version from "7.0.1-A5" to "7.0.1"
> Update share version 7.0.1

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchBasicAuthTests.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchLiveIndexingTests.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchPathIndexingTests.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchReindexingTests.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
This simplifies several tests and also improves some assertion messages which should help us to debug intermittent issues.
> Refactor more tests to use SearchQueryService.

- docker-share/aws/pom.xml
- pom.xml
Upgrade the following:
AIS -> 1.4.0-A1
S3-Connector -> 4.1.0-A2
Azure-Connector -> 2.0.1
> ATS-955 Upgrade AIS, S3-Connector, Azure-Connector

- pom.xml
- tests/pipeline-all-amps/repo/dtas/dtas-config.json
- tests/pipeline-all-amps/repo/pom.xml
- tests/tas-all-amps/pom.xml
- tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
(functionality migrated into Repository and S3 Connector)
> PRODMAN-440 Remove Glacier Connector AMP

- scripts/dev/find-fix.py
This allows determining releases containing the specified commit.
> Update find-fix.py to add -p option.

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchTokenisationTests.java
All the expected behaviours are exactly what happens with SearchServices.
> ACS-2249 Add tests for basic term queries.

- scripts/dev/linkPoms.sh
This is useful when working with remote branches (e.g. origin/master).
Also use loops where same operation is performed on all projects.
> Update linkPoms to have ability to use git fetch.

- pom.xml
- also Azure Connector 3.0.0-A3 (to match common Cloud Connector Base 3.3)
> ACS-2331: Bump to S3 Connector 5.0.0-A4

- pom.xml
- S3 Connector 5.0.0-A5
- Azure Connector 3.0.0-A5
> ACS-2396: Bump ACS Packaging for cloud storage connectors

- docs/custom-transforms-and-renditions.md
- pom.xml
> ACS-2412 Log files flooded with transformation option messages when misconfigured

- scripts/travis/prepare_staging_deploy.sh
This will contain more accurate information than just using the maven modules.
> ACS-2303 Generate distribution license CSV using wars and amps.

- docs/direct-access-urls.md
This PR updates the design of direct access URL feature to include Azure Blob.
The design is subject to small (hopefully) changes resulting from coming implementation.
> ACS-2503: Including Azure Blob in DAU design.

- pom.xml
- tests/environment/.env
- tests/environment/docker-compose-pipeline-all-amps.yml
https://app.travis-ci.com/github/Alfresco/acs-packaging/builds/247644065 passed so PR is created
> DESKTOPAPP- 897: Bump sync service from 3.6.0-A1 to 3.6.0-A2

- pom.xml
Updating Salesforce Version to 2.3.4
> Updating Salesforce Version to 2.3.4

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializer.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchCMISTests.java
Also add potential to debug the Repo when using Testcontainers.
> ACS-2804 E2E test for cmis:objectId field.

- pom.xml
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchCMISTests.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchCMISPathTests.java
See: https://github.com/Alfresco/alfresco-enterprise-repo/pull/825
> ACS-2988 E2E tests for CMIS IN_TREE against ES.

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchCMISTests.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
This PR needs [https://github.com/Alfresco/alfresco-enterprise-repo/pull/840](url) to be merged first in order for the tests to pass.
> ACS-2805: Elasticsearch CMIS - test ORDER BY syntax

- pom.xml
Bump SAML to 1.2.3-A1 for ACS 7.2.N
> ACS-3254 Bump SAML to 1.2.3-A1 for ACS 7.2.N

- pom.xml
Updating Salesforce Alpha version (2.3.6-A2)
> Updating Salesforce Alpha version (2.3.6-A2)

- pom.xml
Bumping SAML version to 1.2.3 _(latest GA)_.
> ACS-3236 Bump SAML to 1.2.3

- distribution/src/main/resources/VERSIONS.md
Travis is now picking up JRE 17.0.4.
> ACS-3347 Update recommended Java 17 version

- .travis.yml
Final release of ACS 7.3.0
Adding [skip tests] in commit message as these have just been run.
> ACS-3660: [release][publish] 7.3.0

- pom.xml
Bump Azure Connector to 3.2.0-A2
> Bump Azure Connector to 3.2.0-A2

- .github/workflows/master_release.yml
> ACS-3843 Fix CI job name

- pom.xml
Bump Azure Connector to `3.2.0-M1`.
> ACS-4378 Bump Alfresco Azure Connector to 3.2.0-M1

- .github/workflows/ci.yml
- tests/testcontainers-env/src/main/java/org/alfresco/tas/AlfrescoStackInitializer.java
- tests/testcontainers-env/src/main/java/org/alfresco/tas/SystemPropertyHelper.java
To use this then specify the indeximage, reindeximage and repoimage variables on the maven command line - for example:
-Dindeximage="quay.io/alfresco/alfresco-elasticsearch-live-indexing:latest" -Dreindeximage="quay.io/alfresco/alfresco-elasticsearch-reindexing:latest" -Drepoimage="alfresco/alfresco-content-repository:latest"
> Add support for running the tests with specified ESC and Repo images.

- .github/workflows/ci.yml
> OPSEXP-1944 Switch to new acs license access & secret keys

- .github/workflows/master_release.yml
- scripts/ci/copy_to_release_bucket.sh
- scripts/ci/maven_release.sh
Ref: OPSEXP-2046
This can be reverted once moving away from `7.4.0-XXXX` and `23.1.0-XXXX`
> OPSEXP-2046 Add base build number to avoid conflicts with previous travis build number

- pom.xml
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchGetTagsTests.java
https://alfresco.atlassian.net/browse/ACS-4023
> Feature/acs 4023 update get /tags to support getting tags by name

- pom.xml
> ACS-4970 Bump AIS to 1.5.0-A4

- .github/workflows/master_release.yml
Final release of ACS 7.4.0
Adding [skip tests] in commit message as these have just been run.
> ACS-4829: [release][publish] 7.4.0

- tests/tas-restapi/pom.xml
Ref. [ACS-5087](https://alfresco.atlassian.net/browse/ACS-5087)
[ACS-5087]: https://alfresco.atlassian.net/browse/ACS-5087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ACS-5087 Add missing awaitility dependency

- pom.xml
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchLimitTests.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
Added TAS tests for tracking total hits on ES
> ACS-5487 Track Total Hits ES

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchLimitTests.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
* Add validation for totalItems in SearchQueryService
* Added tests to test the track hits on v1
(cherry picked from commit 2e38bc86a9624e94832eab3ca69d7d0a0d921fba)
> ACS-5487 Track Total Hits ES (#2513)

- .github/workflows/ci.yml
Bumping DTAS to v1.2.2 which includes more reliable transformer tests.
> ACS-5039 Bump DTAS to v1.2.2

- scripts/ci/prepare_staging_deploy.sh
Remove third party overrides functionality as its not implemented upstream in this version
> Fix release stage

- pom.xml
Bump Azure Connector version to 4.0.0-A3
> [ACS-6089] Bump Azure Connector version to 4.0.0-A3

- .github/workflows/master_release.yml
> [release][publish] 23.1.1 [skip tests][no downstream]

- .github/workflows/master_release.yml
> [release][publish] 7.1.1.9 [skip tests][skip docker_release][no downstream]

- .github/workflows/master_release.yml
> [release][publish] 7.1.1.10 [skip tests][skip docker_release][no downstream]

- .github/workflows/ci.yml
The Share scan issue has been forwarded to Veracode and will be tracked and implemented in a separate ticket when the problem is resolved.
> ACS-6304 Implement SAST Pipeline Scan

- .github/workflows/ci.yml
> ACS-6763: Temporarily disable failing test suite

- tests/environment/.env
- tests/environment/docker-compose-aims.yml
> ACS-7567 Test with Keycloak 24.0.2

- .github/workflows/master_release.yml
> [ACS-7683][release] 7.3.2-A3 version and [skip tests]

- tests/environment/.env
> ACS-7744 Bump Keycloak to 24.0.3

- pom.xml
- tests/environment/.env
- tests/environment/docker-compose-pipeline-all-amps.yml
> bump Sync Service version 3.11.3 in ACS 7.2.N

- .github/workflows/ci.yml
- pom.xml
- tests/tas-all-amps/custom-content-service-context.xml
Bumping S3 connector to 6.1.1-A1 for testing purposes.
> ACS-7893 Bump S3 Connector to 6.1.1-A1 & Azure Connector to 5.0.1-A1

- .github/workflows/master_release.yml
Release `7.3.2-A4` and skip tests 🤞
> ACS-7893 [release] ACS 7.3.2-A4 [skip tests]

- pom.xml
> ACS-7894 ACS-7956 Bump Azure Connector to 5.0.1, S3 Connector to 6.1.1

- scripts/dev/newReleaseBranch.sh
Updated the `community-repo` part in the `modifyOriginalProjectBranchesForNextRelease()` method, to be consistent with other repos.
> [ACS-7890] Update the newReleaseBranch.sh

- .github/workflows/master_release.yml
> [ACS-7890][release][publish] ACS 7.3.2

- scripts/dev/newReleaseBranch.sh
Uncomment the hotfix branch creation line.
> [skip ci] Clean up the newReleaseBranch script

- tests/environment/docker-compose-cmis-elastic-tests.yml
- tests/environment/docker-compose-cmis-opensearch-tests.yml
- tests/environment/docker-compose-pipeline-all-amps.yml
Should help retain compatibility with certain docker-compose V1 versions.
> ACS-8197 Quote booleans in docker-compose

- tests/environment/.env
- tests/environment/docker-compose-pipeline-all-amps.yml
> ACS-8197 Bump alfresco-acs-nginx to 3.4.2

- .github/workflows/arm64.yml
- tests/environment/docker-compose-pipeline-all-amps.yml
Build passed: https://github.com/Alfresco/acs-packaging/actions/runs/9660134238/job/26645058891
> ACS-8228 Increase the proxy memory limit to fix ARM64 failure

- .github/workflows/master_release.yml
> ACS-8288 [skip tests][release] ACS 23.3.0-M1

- distribution/src/main/resources/VERSIONS.md
- pom.xml
- tests/pipeline-all-amps/repo/Dockerfile
- tests/pipeline-all-amps/repo/dtas/dtas-config.json
- tests/pipeline-all-amps/repo/pom.xml
- tests/tas-all-amps/pom.xml
- tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
https://hyland.atlassian.net/browse/ACS-8147
> ACS-8147: Add hxi-connector to acs-packaging

- pom.xml
https://hyland.atlassian.net/browse/ACS-8147
> ACS-8147: Add hxi-connector to acs-packaging - bump to v. 1.0.0-A7

- pom.xml
- tests/environment/.env
> ACS-8421 Bump Transform Core to 5.1.4-A1 + Service to 4.1.4-A1 + AIS to 3.1.6-A1 & ES to 4.1.0-A9

- .github/workflows/ci.yml
- tests/pipeline-all-amps/repo/Dockerfile
- tests/pipeline-all-amps/repo/docker-entrypoint.sh
Copy of https://github.com/Alfresco/acs-packaging/blob/d3ffba66eeab1347ab5014ecec4130aae0df300a/.github/workflows/ci.yml#L501 adjusted for Java 21
> [ACS-8884] Add Distribution Zip content tests  against Java 17 and 21

- pom.xml
I have Upgrade the salesforce connector version 4.0.0-A1
> I have Updated the Salesforce Version

- pom.xml
Update Salesforce version 3.2.0-A1
> Update Salesforce version 3.2.0-A1

- scripts/ci/build.sh
- tests/environment/alfresco-with-jdbc-drivers/alfresco.Dockerfile
https://hyland.atlassian.net/browse/ACS-9037?focusedCommentId=2221144
> ACS-9037 Use correct Repo latest image

- scripts/ci/build.sh
- tests/environment/alfresco-with-jdbc-drivers/alfresco.Dockerfile
(cherry picked from commit a25d7df87b4a4cc10647ba64d2e9458fff7dad5a)
> ACS-9037 Use correct Repo latest image (#2997)

- .github/workflows/ci.yml
https://github.com/onnx/tensorflow-onnx/pull/2376
> [ACS-9108] Bumped python version 3.7.15 -> 3.8.12

- scripts/ci/build.sh
- tests/environment/alfresco-with-jdbc-drivers/alfresco.Dockerfile
I believe its needed to fix https://github.com/Alfresco/acs-packaging/actions/runs/13177976253/job/36786980715
> [ACS-9202] Backport ACS-9037 to release/23.N

- scripts/ci/build.sh
- tests/environment/alfresco-with-jdbc-drivers/alfresco.Dockerfile
I believe its needed to fix https://github.com/Alfresco/acs-packaging/actions/runs/13178010937/job/36786890472
> [ACS-9202] Backport ACS-9037 to release/7.4.N

- tests/tas-restapi/src/test/resources/restapi-aims-suite.xml
- tests/tas-restapi/src/test/resources/test-suites/part2-suite.xml
Exluded tests that should run only in community edition.
> ACS-9178 Exclude community-only tests for people endpoint

- pom.xml
- tests/tas-integration/pom.xml
Ref. https://github.com/Alfresco/alfresco-community-repo/pull/3207
Note: Remove `SNAPSHOT` versions before merging to master.
> ACS-9199 Bump subethasmtp version / use angus-mail

- docs/micrometer/Alfresco_Enterprise_Authentication_Dashboard.json
- docs/micrometer/README.md
- updated documentation
- added Grafana dashboard
The Grafana dashboard example can be find in ticket comment: [MNT-24860](https://hyland.atlassian.net/browse/MNT-24860?focusedCommentId=2290397)
[MNT-24860]: https://hyland.atlassian.net/browse/MNT-24860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MNT-24860 Prometheush AUTH metrics

- tests/tas-integration/pom.xml
This reverts commit f0d60ff36fb7ca3bfea51f5ab4338cb6f4e15e2f.
> Revert "ACS-9199 Use angus-mail (#3052)"

- .github/workflows/arm64.yml
OPSEXP-3069
tested on https://github.com/Alfresco/acs-packaging/actions/runs/13766627264
> OPSEXP-3069 Switch to default arm64 runners

- .github/workflows/master_release.yml
…release] just run [no downstream] enterprise only
> [MNT-25034][release][publish] HotFix 23.3.7 [skip tests][skip docker_release] just run [no downstream] enterprise only

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/FromLegacyAcsUpgradeTest.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/FromSolrUpgradeTest.java
More information about this change: https://hyland.atlassian.net/browse/ACS-9856
> ACS-9856 Improve stability of acs-packaging ES TAS tests

- tests/environment/alfresco-mtls/Dockerfile
See https://github.com/Alfresco/acs-packaging/pull/3178
> Fix MTLS Dockerfile to use local image
