- distribution/src/main/resources/VERSIONS.md
This PR updates the SalesForce Connector version to 2.1.0-RC1 in the VERSIONS.md file.
JIRA issue: https://issues.alfresco.com/jira/browse/SFDCENG-748
> SFDCENG-748 : Generate RC1 for SalesForce 2.1.0 compatible with ACS 6.0

- pom.xml
- Previously forgot to update dependency alfresco-messaging-repo to 1.2.9
> APPSREPO-433 : Update dependencies in acs-packaging

- pom.xml
- update the SF connector version to 2.1.0-RC2
> SFDCENG-756 : Generate RC2 for Salesforce 2.1.0 compatible with ACS 6.0

- docker-alfresco/test/docker-alfresco-all-amps-test/pom.xml
- pom.xml
- added Document Transformation Engine amp to the list of applied amps. Updated version to 2.2.0
> REPO-3590: 6.0: Include Document Transformation Engine amp into "all amps" test

- docker-alfresco/Dockerfile
- docker-alfresco/aws/pom.xml
- docker-alfresco/pom.xml
- All licenses (including 3rd party) should be under `/licenses` directory of the docker image.
> REPO-4172: Add Licenses directory to the root of docker image

- docker-alfresco/test/docker-alfresco-all-amps-test/pom.xml
- pom.xml
This means removing the SAML and MM module from the all-amps docker image and tests since they need to be fixed and released separatly
> REPO-4135: upgrade hazelcast to the latest version 3.11.2 

- docker-alfresco/test/docker-alfresco-all-amps-test/scripts/checkLibraryDuplicates.sh
- pom.xml
Added `org.apache.camel dependencies`, version 2.23.2
After the upgrade, the test on the duplicate library failed, but it was not a valid case, so I did some changes to the script that does this duplication check:
* added a whitelist of library names, in order to fix the false positives that are reported for libraries that don't follow naming/versioning standards.
* refactored the script, for consistent naming style.
> REPO-4369: Add org.apache.camel dependencies, version 2.23.2

- docker-alfresco/test/docker-alfresco-all-amps-test/scripts/checkLibraryDuplicates.sh
Added a whitelist of library names, to the script that checks for duplicate libraries, empty for now, but could be useful to bypass false positives reported for libraries that don't follow naming/versioning standards (this is used on 6.0.N branch already).
Refactored the script, for consistent naming style.
> Add a whitelist of library names, to the script that checks for duplicate libraries

- pom.xml
- updated alfresco-messaging-repo to version 1.2.13 which brings camel libs 2.23.2 and activemq libs 5.15.9
> APPSREPO-651 : [Security] MNT-20533: activemq-client MitM vulnerability

- docker-alfresco/Dockerfile
- pom.xml
- war/src/main/resources/log4j.properties
Integrated the jmxlogger into the log4j.properties file from acs-packaging. 
jmxlogger was previously configured in the alfresco-enterprise-repository project (in a repository-log4j.properties file that was removed with this fix)
Also, in the docker image, I moved the alfresco.log file to the tomcat/logs folder and fixed the permissions for the folders to make the docker image more secure
> REPO-4278 Service Pack: MNT-18557 Location Of alfresco.log is Ultimately Incorrect

- .gitignore
- distribution/src/main/resources/keystore/CreateSSLKeystores.txt
- distribution/src/main/resources/keystore/generate_keystores.bat
- distribution/src/main/resources/keystore/generate_keystores.sh
- distribution/src/main/resources/keystore/readme.txt
In removing the ssl.keystore and ssl.truststore the following files were found. It would be more appropriate for these to be part of packaging.
> REPO-4400: Moving keystore folder contents

- pom.xml
Update enterprise-alfresco-repository to 6.36.22 (hazelcast upgrade revert)
> REPO-4503: Revert Hazelcast upgrade on 6.0.N

- pom.xml
Update libraries:
alfresco-core to 7.5.6
alfresco-data-model to 8.18.11
alfresco-repository to 6.56.32
alfresco-remote-api to 6.39.22
alfresco-enterprise-repository to 6.36.24
alfresco-enterprise-remote-api to 6.28.17
> REPO-4504 Update cxf to 3.3.2

- war/src/main/resources/log4j.properties
Followup of https://github.com/Alfresco/acs-community-packaging/pull/258
> Remove trailing whitespaces in log4j.properties

- docker-alfresco/aws/pom.xml
- include the Sync service AMP into the 'alfresco-content-repository-aws' image
> APPSREPO-673 : Sync service included into ACS part II

- CHANGELOG.md
- distribution/src/main/resources/licenses/notice.txt
- Discussions & Blogs no longer removed.
- xmlrpc has been removed in 6.1.1, so should not be in notice.txt
> REPO-4675 Reinstate removed deprecated functionality for ACS6.2: Add Blogs (acs-packaging)

- pom.xml
Bump S3 connector version to 3.0-RC4
Bump Glacier connector version to 2.0.0-RC1
> Bump Glacier and S3 connectors versions

- distribution/src/main/resources/VERSIONS.md
- docker-alfresco/test/docker-alfresco-all-amps-test/pom.xml
- pom.xml
- first attempt for AGS 3.2.0 on ACS 6.2.0 (hence branched from "support/SP/6.2.N")
- ... if successful then also merge up to master (ie. AGS 3.2.0 on ACS 6.3.0-SNAPSHOT)
> RM-7056: Add AGS to ACS Packaging "all-amps" startup test

- pom.xml
- war/pom.xml
Bring in the ACS 6 compatible activiti-repo-connector.jar as a dependency of acs-packaging. Code is enabled by setting an alfresco-global.property activitiRepoConnector.enabled=true
https://github.com/Alfresco/activiti-bpm-suite/tree/develop/integrations/alfresco
> REPO-4924 Add "Start Activiti Process" Action to repository codebase

- pom.xml
Bump data-model to 8.50.2.1
Bump alfresco-repository to 7.134.5
Bump alfresco-remote-api to 7.107.2
Bump alfresco-enterprise-repository to 7.69.3
Bump alfresco-enterprise-remote-api to 7.54.2
> MNT-21472 : Space in Windows installation path cause FileNotFound

- pom.xml
- as requested by Preeti N
- to run "all-amps" startup test (~ ACS 6.2.1)
- note: we will leave master using 2.2.0-EA1
> SFDCENG: set back to Salesforce Connector 2.1.0.1 (for now)

- pom.xml
Currently ACS 6.2.1-RC3 contains a reference to rest-api-explorer 6.3.0. This is wrong. There is a released 6.2.1 version but there have been more commits since. This PR updates 6.2.N in order to use 6.2.1.1 version (released 29/04/20) which include these additional commits.
> ACS-100 Update api-explorer to 6.2.1.1 into 6.2.N

- war/pom.xml
cors-filter jar was missing in 6.2.1 release. ACS fails to start if CORS is enabled(cors.enabled=true) in alfresco-global.properties because of the missing jars.
https://issues.alfresco.com/jira/browse/MNT-21430
> MNT-21430-Added cors-filter dependency

- pom.xml
- note: requires ATS (T-Router) 1.3.0-A2 (or higher)
> ATS-761: Bump to AIS 1.2.0-A1

- docs/custom-transforms-and-renditions.md
This customer issue was about how to override Legacy transforms, but highlighted that the same operation was missing from the new approaches docs.
> MNT-21479 Add "Overriding a transform" to the new way of overriding transforms

- pom.xml
- tests/environment/docker-compose-all-amps-test.yml
- tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
- Bump Azure Connector to `1.1-RC1` and use default `sharedKey` authentication mode in CI/CD pipeline
Note: While making changes below was observed:
```
{"id":"org_alfresco_module_rm","title":"AGS Repo","description":"Alfresco Governance Services Repository Extension","version":"3.3.1","installState":"UNKNOWN","versionMin":"6.2","versionMax":"999"}
{"id":"alfresco-ai-repo","title":"Alfresco Intelligence Services Repository AMP","description":"Extensions in Alfresco Repository for the Alfresco Intelligence Services","version":"1.1.2","installState":"UNKNOWN","versionMin":"6.2.0","versionMax":"6.99.99"}
{"id":"alfresco-trashcan-cleaner","title":"alfresco-trashcan-cleaner project","description":"The Alfresco Trashcan Cleaner (Alfresco …
```
> REPO-4641: Azure Connector supports more authentication options

- pom.xml
- tests/tas-all-amps/pom.xml
- tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
- Add direct dependency in acs-packaging
- Comment out the MM amps, which are incompatible with the new metadata-extractor version
> ACS-370: Newer metadata-extractor (2.13.0)

- pom.xml
- tests/tas-all-amps/pom.xml
- tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
- update MM version from 1.4.1 to 1.4.2-RC1
- enable MM AMPs in the tas-all-amps module
> ACS-381: MM 1.4.2-RC1 release

- tests/scripts/wait-for-alfresco-start.sh
From the analysis done in ACS-222, adding an extra interval (before tests start) seems to prevent the jobs to fail - not only the AIMS jobs but also the other ones that already failed before ACS-222 (even that not very often).
> ACS-222: tests jobs using AIMS fail

- pom.xml
- AIS service pack - targeting ACS 6.2.2 (as part of S/H release train)
> ATS-808: Bump AIS to 1.2.1-RC2

- distribution/pom.xml
- excluded the keystore contents from filtering
> MNT-21875 : [PaaS] Alfresco Content Services 7.0.0 M1 Distribution contains invalid Keystore

- .travis.yml
- docker-alfresco/Dockerfile
- docker-alfresco/aws/pom.xml
- docker-alfresco/pom.xml
- pom.xml
- tests/environment/docker-compose-aims.yml
- tests/environment/docker-compose-all-amps-test.yml
- tests/environment/docker-compose-cluster.yml
- tests/environment/docker-compose-cmis-tests.yml
- tests/environment/docker-compose-email-tests.yml
- tests/environment/docker-compose-integration-tests.yml
- tests/environment/docker-compose-minimal.yml
- tests/environment/docker-compose-node-restart.yml
- tests/environment/docker-compose-pipeline-all-amps.yml
- tests/environment/docker-compose-rest-api-tests.yml
- tests/environment/docker-compose-sync-service.yml
- tests/environment/docker-compose-with-ldap.yml
Contents of the PR:
* Copy the old keystore into the docker image from distribution zip
* Configure docker environments to use old keystore's config as JAVA_OPTS
* Remove redundant enterpriseDocker maven profile as it is the same as fullBuild because of the dependency on the distribution zip.
> MNT-21859 Embed old keystore in docker images

- pom.xml
- tests/tas-integration/src/test/java/org/alfresco/tas/integration/IntegrationWithWebScriptsTests.java
- Bump `alfresco-sprint-webscripts` to `8.10` which contain CSRF filter fix
- `alfresco-repository` to `8.283` which also brings surf-webscripts (`8.10`)
- Remove extra `/` in alfresco URI when `RestAssured.basePath` is set empty
- Bump `alfresco-data-model` to `8.154` which contains the reversion of `opencmis:1.0.0` (to avoid clash/conflicts when `alfresco-repository` and `alfresco-data-model` brings different versions of `opencmis` in this project).
> ACS-525: org.alfresco.surf:spring-webscripts:8.8 & acs-packaging test failure

- pom.xml
The version in remote-api is still 2.10.1 and the upgrade has failing tests (https://github.com/Alfresco/alfresco-remote-api/pull/776).
The update was originally done by dependabot #1598
> MNT-21871: Revert jackson-databind from 2.11.2 back to 2.10.1

- tests/tas-email/src/test/java/org/alfresco/email/imap/ImapReadMessagesAscTests.java
Part of Epic: ACS-959 Fix or suppress the content repository's intermittent test failures
> ACS-960 Disable very frequent intermittent test failures

- .travis.yml
- pom.xml
- updated `acs-packaging`, for `6.2.N` with `azure-1.2.0-A4` compatible with both ACS 6.2 and 7
> ACS-857 : Azure Connector 1.2 Alpha Release

- tests/pipeline-all-amps/share/Dockerfile
Fixes java.security.AccessControlException on GraalDetector at startup of share pipeline all amps docker image
> fix share pipeline all amps image exception startup

- tests/pipeline-all-amps/pom.xml
As publishing images happens on the maven install phase for all the images but the pipeline ones, moving push from deploy to install would fix ACS-1077
> ACS-1077 push pipeline images in install phase

- dev/dev-acs-amps-overlay/pom.xml
- dev/dev-tomcat/pom.xml
- dev/pom.xml
- distribution/pom.xml
- docker-alfresco/aws/pom.xml
- docker-alfresco/pom.xml
- docs/create-custom-image.md
- pom.xml
- scripts/travis/init.sh
- tests/pipeline-all-amps/pom.xml
- tests/pom.xml
- tests/tas-all-amps/pom.xml
See ACS-1110, build docker images with docker-maven-plugin so that there are no warnings for rogue connections to a not existing kubernetes cluster
```log
[INFO] --- fabric8-maven-plugin:4.4.0:build (build-image) @ alfresco-pipeline-all-amps-repo ---
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] F8: Cannot access cluster for detecting mode: Unknown host kubernetes.default.svc
[INFO] F8: Running in Kubernetes mode
[INFO] F8: Building Container image with Docker in Kubernetes mode
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring. …
```
> ACS-1110 replace fabric8 with docker-maven-plugin

- .travis.yml
- add the `skip_cleanup: true` option so that Travis doesn't execute `git stash --all` before the S3 upload
> Fix TravisCI deploy options for the S3 Staging bucket upload [skip ci]

- pom.xml
- tests/pipeline-all-amps/repo/pom.xml
- tests/pipeline-all-amps/share/pom.xml
- tests/tas-all-amps/pom.xml
- tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
Also removed the DTE AMPs as there should not be a Repo on in 7.0.0 and we don't know about Share.
As a result of comments of this PR, desktop sync and AGS (rm) have been reintroduced to the DiscoveryTests and removed the commented out DTE. More tests will fail, but the code is more complete once these AMPs are fixed.
> The Single pipeline jobs should not have any commented out AMPs.

- CHANGELOG.md
- docs/custom-transforms-and-renditions.md
* Add more description on how to override renditions and even disable them.
* General tidy up of custom-transforms-and-renditions.md following the ACS 7.0.0 changes.
> MNT-21817 Selectively disable renditions to avoid extra load

- .travis.yml
- tests/environment/docker-compose-pipeline-all-amps.yml
- tests/environment/dtas-config.json
- tests/pipeline-all-amps/repo/dtas/dtas-config.json
- tests/pipeline-all-amps/repo/pom.xml
- Removed Centera AMP as it's not used in the pipeline
- Fix S3 connector config & use custom admin username but default password
- Fixed startup script (was passing even though system was failing to start)
- Run DTAS after system is running
NOTE: The AGS AMP does not report the same version as the artefact version so it had to be hardcoded in DTAS config. Same for ACS version, but that shouldn't change as often.
> OPSEXP-718: Use DTAS for smoke testing the pipeline-all-amps-repo image

- .travis.yml
Elasticsearch TAS Test can be re-enabled since SEARCH-2872 has been resolved.
> SEARCH-2870: Re-enable Elasticsearch TAS Tests

- dev/checkout.sh
Note that this script will only be present in versions after this commit.  Unfortunately this
means that if you change to a release older than this commit then it will be slightly awkward
to get back again. (Something like git checkout origin/master and then rerunning the script
will work though).
> Add script to enable changing between versions of acs projects.

- pom.xml
- bump S3 Connector 5.0.0-A1 and Azure Connector 3.0.0-A1 (both using Cloud Connector Base 3.1)
- both compatible with Repo 7.2.0-A5
- note: also fixes ACS-2022 (for int pipeline)
> ACS-2145: Bump Connectors (S3 to 5.0.0-A1 & Azure to 3.0.0-A1) (for Repo 7.2.0-A5)

- scripts/dev/find-fix.py
I wanted to do more than this, but I think this is significantly better than nothing.  Example usage:
```
$ ./acs-packaging/scripts/dev/find-fix.py -j "SEARCH-3049"
0939e81d794ce6f337525782476a3676f4b500c3 is in alfresco-enterprise-repo: 14.8
d6e1e3ec1bbd4f0818282d342dc3eb080aaf28b9 is in acs-packaging: 7.2.0-A1
```
Hotfix example:
```
$ ./acs-packaging/scripts/dev/find-fix.py -j "REPO-5359" -r
3795fcd3efd56e6ef59ac2ef46a0b7b9a651be1a is in acs-packaging: 6.0.0.6
9bca10fa72263cbf7831e6987015814e8424c050 is in acs-packaging: 6.0.1.7
2fc2e5d249d393aa8f571a6564d008841b87c046 is in acs-packaging: 6.1.0.10
1d596f096e73112292142e67199b2ac71a9c949d is in acs-packaging: 6.1.1.8
25ac63e8ae7d2b1e8f6bbc4baee53f66ff917a0d is in acs-packaging: 6.2.0.7
94db72436942ba6e4d0d853bd55e15105e9b309d is in …
```
> Python script to find the releases containing a fix.

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/basicAuth/AlfrescoStackInitializerESBasicAuth.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/basicAuth/ElasticsearchBasicAuthTests.java
- tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-basic-auth-suite.xml
- tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-suite.xml
use package reference in test suite instead of classes
refactor tests: move ES basicAuth test to dedicated package
> ACS-2171 use package reference in test suite instead of classes

- pom.xml
- S3 Connector 5.0.0-A3 (inc ACS-2222)
- Azure Connector 3.0.0-A2
- note: both targeting ACS Repo 7.2.0-A7
> ACS-2297: Bump ACS Packaging (for S3 & Azure)

- .travis.yml
- tests/tas-elasticsearch/src/test/resources/log4j.properties
- tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-suite.xml
log4j: log level to debug
testng: verbose to 1
> ACS-2441 - adjust log levels for TAS-based ES tests

- pom.xml
- targeting ACS Repo 7.2.0-A12 (or higher)
> ACS-2287: Bump Azure Connector to 3.0.0-A7 (from 3.0.0-A5)

- .travis.yml
After changes from comm-repo [PR#908](https://github.com/Alfresco/alfresco-community-repo/pull/908) a release is needed.
As a follow-up there will be a fix and release in Azure Connector project.
> ACS-2104: [release] 7.2.0-A23

- .travis.yml
- includes:
- https://app.travis-ci.com/github/Alfresco/acs-packaging/builds/246890724
- https://github.com/Alfresco/acs-packaging/commit/efa66963c14a77026450c5613fbd23d03c47b73d
- com-repo 14.114 (with Camel 3.15.0 / Netty 4.1.73.Final)
- ent-repo 14.109
- ent-share 14.71
> ACS-2476: [release] 7.2.0-A24 [skip tests] as they have just run

- scripts/travis/build.sh
Test ensures the build will go red after each HF is released and also stops us from just using the next number in sequence (which we have done several times) without going back to change a setting in enterprise repo and waiting several hours for builds.
> Build should not go red after each release - a test too far

- tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
Now it's a regex split based on non-decimal characters to get the semantic version (major, minor, patch)
> ACS-2749: Replaced straight charAt usage

- scripts/dev/start-compose.sh
The `envUp` alias is now unusable from the parent directory, as opposed to the previous behaviour _(documented [here](https://github.com/Alfresco/acs-packaging/blob/master/dev/README.md?plain=1#L76-L79))_. This PR restores the original behaviour.
> Fix broken 'envUp' alias

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchCMISTests.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
- within acs-packaging (via V1 REST Search API using "cmis" query lang)
- note: currently Search API returns generic 500 (rather than 400) for invalid queries (whether syntactic or semantic)
> ACS-2985: Elasticsearch CMIS - a few basic +ve/-ve tests

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializer.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchCMISTests.java
Along with adding the `queryContistency` property and removing the `CONTAINS('*')` clauses, I have also removed 2 tests. The one testing queries to the DB is now redundant, whereas the second one should be added again once ACS-2920 is solved.
> ACS-2803: Prevent  CMIS tests queries from going to the database 

- scripts/dev/newReleaseBranch.sh
- tests/pipeline-all-amps/repo/dtas/dtas-config.json
Script to creates HotFix and ServicePack (.N) branches for repo, share and packaging projects, and updates the master or ServicePack branches ready for the next release.
- This script may be used following releases >= 7.2.1.
- Master must have been used for major or mion releases and .N branches for service pack releases.
https://alfresco.atlassian.net/wiki/spaces/TECH/pages/962298737/ACS+Release+Process+-+Creating+the+branches+after+a+release
This script will be cherry picked back to release/7.2.N
> ACS-2864 Script the creation of new repo, share and packaging branches after an ACS release

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializer.java
- update tas-elasticsearch tests (via TestContainers) to override new "query.cmis.queryConsistency" (instesd of deprecated "solr."query.cmis.queryConsistency") prop
- note: follow-on to:
-- https://github.com/Alfresco/alfresco-community-repo/pull/1089
-- https://github.com/Alfresco/alfresco-enterprise-repo/pull/800
> ACS-2925: Elasticsearch - refactor DB switching to not use Solr-specific properties

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchCMISTests.java
> ACS-2808 Elasticsearch CMIS E2E tests for "IS NULL" and "IS NOT NULL" syntax

- pom.xml
Bumping Alfresco SAML to the latest version _([1.2.3-A1](https://github.com/Alfresco/alfresco-saml-module/releases/tag/1.2.3-A1))_.
> ACS-3254 Bump Alfresco SAML to 1.2.3-A1

- tests/environment/docker-compose-pipeline-all-amps.yml
The original ticket asked for upgrade to 2.2.0 but this is out of date.
Code changed to use the version in .env which is currently 2.7.0.
The Single Pipeline image tests successfully pulled and started `quay.io/alfresco/alfresco-digital-workspace:2.7.0`.
> Use version of alfresco-digital-workspace from .env (2.7.0)

- .travis.yml
- pom.xml
- tests/scripts/checkLibraryDuplicates.sh
In scope of updating camel library and moving netty dependency declarations to community-repo, I needed to release azure-connector 3.0.1-A1
> ACS-3402: update version of azure-connector to 3.0.1-A1

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
For some reason TestNG doesn't do this by default.
> ACS-3448 Output expected and actual values for Elasticsearch queries.

- tests/tas-integration/pom.xml
Integration TAS tests will require reflective access to `java.lang` once the migration to Log4j2 is complete, example of a failing build with Log4j2: https://app.travis-ci.com/github/Alfresco/acs-packaging/jobs/586708111#L800.
> ACS-3160 Open java.lang for Integration TAS tests

- scripts/travis/build.sh
These `MAVEN_OPTS` to open reflective access at compile time were necessary when Share was not compatible with Java 17 yet. It's safe to assume this workaround is not needed anymore since Share has been upgraded to be compatible with Java 17.
> APPS-1677 Remove unnecessary MAVEN_OPTS when building Share

- pom.xml
Bump Azure Connector to the latest version relying on Log4j 2.x.
> ACS-3871 Bump Azure Connector to 3.2.0-A1

- .github/workflows/ci.yml
- scripts/ci/wait-for-alfresco-start.sh
Temporarily show full Docker logs instead of last 200 lines, in order to better investigate DependaBot PR failures such as: https://github.com/Alfresco/acs-packaging/actions/runs/3967360229/jobs/6799228445
> Improve logs to investigate DependaBot PRs failures

- pom.xml
Manually bump upstream repo versions until `alfresco-enterprise-share` build is fixed to work well with GHA.
> Bump upstream repo versions

- .github/workflows/ci.yml
- .github/workflows/master_release.yml
Bumping alfresco-build-tools to v1.32.0 and updating the veracode action accordingly.
> ACS-3750 Bump alfresco-build-tools to v1.32.0

- .github/workflows/ci.yml
This was frequently failing when used with MS SQL.
> Increase the timeout for ES tests.

- .github/workflows/ci.yml
- .github/workflows/master_release.yml
Replace `contains` with `startsWith` for better branch detection.
> ACS-3750 Improve branch detection in if conditions

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchCategoriesCountTests.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchCategoriesCountTests.java
https://alfresco.atlassian.net/browse/ACS-4154
- added tests related with count field for categories API in context of ElasticSearch
> ACS-4154: Add category count to relevant CRUD endpoints for categories

- .github/workflows/ci.yml
This is a short term fix for a disk space problem for the tests using Oracle Database Image.
In the fix some unnecessary files are removed from the GHA Runner.
> Investigate failures for ES&Oracle builds

- .github/workflows/ci.yml
Noticed this while reviewing https://github.com/Alfresco/acs-packaging/pull/2400
> Use S3 pipeline secrets only where they are really needed

- docker-alfresco/Dockerfile
- docker-alfresco/ags/Dockerfile
- docker-alfresco/aws/Dockerfile
- docker-share/aws/Dockerfile
- pom.xml
- tests/scripts/checkLibraryDuplicates.sh
This is a workaround for a circular dependency between acs-packaging and amps. Should be reverted when AMPs are released and integrated into the acs-packaging.
> ACS-4844 Temporarily force amps installation

- scripts/ci/copy_share_image_to_docker_hub.sh
This PR it to make the `copy_share_image_to_docker_hub.sh` script able to copy a multi-arch share image to dockerhub.
> ACS-4139 Copy multi-arch share image to dockerhub

- pom.xml
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchLiveIndexingTests.java
We no longer escape asterisks in wildcard queries - add tests for this.
> ACS-4818 Tests for wildcard queries.

- pom.xml
Fixes lib collisions between the ACS repo and AMPs.
> ACS-4970 Bump Azure Connector to 3.2.0-A7

- .github/workflows/master_release.yml
Newly created tag was not being able to be checked-out
> GHA Workflow on master/release - Fix publish stage 

- pom.xml
To test compatibility with the latest Camel bump.
**NOTE:** it seems there are issues with the latest Camel bump, which will be reverted and this PR will be re-used to bump Azure Connector to a 3.3.0-Ax with an appropriate version of enterprise-repo as parent.
> ACS-4955 Bump Azure Connector to 3.3.0-A3

- pom.xml
- tests/tas-cmis/pom.xml
Overrides seem to be now unnecessary even though they were introduced to address https://alfresco.atlassian.net/browse/ACS-3604.
> ACS-4955 Remove unnecessary resteasy version overrides

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchGetTagsTests.java
- tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-suite.xml
https://alfresco.atlassian.net/browse/ACS-5426
> ACS-5426: ElasticsearchGetTagsTests fails on acs-packaging

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchBoostedSearchTests.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchTemplateSearchTests.java
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
E2E tests verifying search boosts functionality for ElasticSearch.
https://alfresco.atlassian.net/browse/ACS-4799
> ACS-4799: Elasticsearch query feature expansion - boosts

- .github/workflows/ci.yml
https://alfresco.atlassian.net/browse/ACS-5722
Adding docker-dump-containers-logs to ACS Packaging CI for elasticsearch tas tests
> ACS-5722 Dump Docker logs on ES tas tests failure

- .github/workflows/master_release.yml
As discussed - `docker_release` CI job is removed (already done in applicable `release/7.x.y` branches)
> ACS-5273: Removing docker_release job

- scripts/ci/jira/jira_integration.py
As per title, the ARM64 Jira integration should be able to close previously created tickets even if they're in Review/Verify status.
Tested here: https://github.com/Alfresco/acs-packaging/actions/runs/5749195631/job/15583558417
It successfully closed this issue that was in **Verify** status: https://alfresco.atlassian.net/browse/ACS-5762
> ACS-5778 ARM64 Jira integration should close tickets in Review/Verify status

- .github/workflows/ci.yml
This also updates the default ruleset location from AlfrescoLabs/pmd-ruleset to Alfresco/pmd-ruleset.
> PRODENG-222 Update to PMD 7.

- .github/workflows/master_release.yml
Releasing a new -Ax of acs-packaging to include the multi-arch ATS images for test purposes.
> ACS-5039 [release] ACS 23.1.0-A27 [force][skip tests]

- .github/workflows/ci.yml
- pom.xml
- tests/pipeline-all-amps/repo/Dockerfile
- tests/pipeline-all-amps/repo/docker-entrypoint.sh
Repeating both the Zip distribution tests and the Single Pipeline image (with all AMPs) tests with both Java 11 and 17 as opposed to Java 17.
This should help identifying issues with lack of backwards compatibility with Java 11 at CI/CD time.
>**NOTE:** the build currently fails due to GitHub issues + Java 11 incompatible version of surf webscripts present in community-repo and enterprise-share, I believe it's safe to merge even now as it's been proved to work against special versions of comm-repo / ent-share.
**Tests**:
- [Zip distribution (Java 11)](https://github.com/Alfresco/acs-packaging/actions/runs/6076160720/job/16494840865)
- [Zip distribution (Java 17)](https://github.com/Alfresco/acs-packaging/actions/runs/6076160720/job/16494840935)
- [Single pipeline all AMPs (Java …
> ACS-5951 Add Java 11 compatibility tests

- pom.xml
- tests/environment/.env
> ACS-5944 ACS-5960 Bump ATS & ES to the latest -Mx

- scripts/ci/jira/jira_integration.py
The JIRA integration used within the arm64 workflow fails with `Error in the JQL Query: Expecting either 'OR' or 'AND' but got 'Borealis'. (line 2, character 34)` due to the release train containing a whitespace and not being properly quoted.
This should address the issue.
**Example failure**: https://github.com/Alfresco/acs-packaging/actions/runs/6256641849/job/16988051747#step:4:63
**Example run after the fix**: https://github.com/Alfresco/acs-packaging/actions/runs/6258693313
> ACS-6054 JIRA integration now works with >1 word release trains

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchBoostedSearchTests.java
When testing manually, I was not able to get the expected order of results even for older versions of ACS such as `23.1.0-M4`. The expected order of results was possible after changing the values in the query.
> Fix Elasticsearch Boosted Search Test

- pom.xml
- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchHighlightingTests.java
- E2E tests
More info: https://alfresco.atlassian.net/browse/ACS-6070
> ACS-6070: Support for highlighting prefix and postfix

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/NodesSecondaryAncestorIndexingTests.java
Disabling a test we already identified as intermittent failure (ACS-6112). Skipping tests as nothing but test ignore annotation has been added.
> ACS-6112: Ignoring test which fails intermittently. [skip tests]

- .github/workflows/ci.yml
Temporarily removing MS SQL Elasticsearch E2E suite from pipeline (as per ACS-6177).
> ACS-6177: [skip tests] Disabling Elasticsearch MS SQL E2E tests.

- tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/NodesSecondaryAncestorIndexingTests.java
- tests/testcontainers-env/src/main/java/org/alfresco/tas/AlfrescoStackInitializer.java
Re-enable testSecondaryAncestorWithNodeHavingComplexSecondaryRelationship
- open debug port for live-indexer in E2Es
> ACS-6112: re-enable disabled test

- .github/workflows/ci.yml
These jobs require real 23.2 license. Since we are not going to generate new licenses for this version (23.1 license should be used for 23.X). These jobs should be restored after introducing new versioning scheme to the repo.
> Disabling jobs requiring new license

- .github/workflows/arm64.yml
- tests/pipeline-all-amps/repo/dtas/dtas-config.json
Changing the approach we use to do ARM64 tests in ACS Packaging.
We rely on a permanently deployed EC2 runner which is easily subject to degradation over time and incurs in issues which usually result in having to reboot the runner manually or recreate it altogether. Also, this kind of runner doesn't allow parallel builds and must be cleaned thoroughly before/after the execution as it's not disposable.
We rely on an on-demand EC2 runner that is created, set-up, used to run the tests and is finally destroyed - on the fly. This also allows parallel runs with multiple runners with no additional effort.
Also, I commented out the `test_adw_reachability` as it was failing, most likely due to the fact that ADW is emulated and therefore very slow => the test is also irrelevant, it should be …
> ACS-6282 Switch to a disposable EC2 hosted runner for ARM64 tests

- scripts/dev/newReleaseBranch.py
This python script mimics the behavior of the shell script we used for new branch creation after ACS release but it is adjusted to new ACS versioning schema. 
Additionally, script gives opportunity to create release branches before the release is done so that we don't need to freeze the code. 
It is written in python mostly because it gives more control of processing output and error handling.
As I have revisited python after many years, I am open to any suggestions.
> ACS-6406 new release branch script adjusted to new ACS versioning schema

- scripts/ci/jira/jira_integration.py
Relaxing the filter to guess the current train as sometimes there are no Epics to pick from, but Stories/Tasks/Sub-tasks instead may be available.
**Tested here:** https://github.com/Alfresco/acs-packaging/actions/runs/8111459674/job/22171289846 ✅
> Fix JIRA integration unable to identify current train

- .github/workflows/ci.yml
To avoid CMIS (BROWSER binding) / CMIS (ATOM binding) TAS tests timeouts there is a need to increate timeout to 1h.
> ACS-7513 Increase CMIS (BROWSER binding) / CMIS (ATOM binding) TAS tests timeout

- pom.xml
As per title, bumping the S3 connector version for tests so that we can better guarantee compatibility with 5.1.0.
Also verified compatibility in the S3 connector repository via https://github.com/Alfresco/alfresco-s3-connector/actions/runs/8986658359 ✅
> ACS-7712 Bump S3 connector to 5.1.0

- .github/workflows/ci.yml
With the latest Docker 26.x, certain combinations of Docker Image Format/Manifest/Schema version have been deprecated: [Deprecated Engine Features](https://docs.docker.com/engine/deprecated/#pushing-and-pulling-with-image-manifest-v2-schema-1).
This PR is to add a temporary fix.
> ACS-8279 Add a temporary fix for unsupported Docker Image Format/Manifest/Schema combinations

- .github/workflows/ci.yml
As the images for oracle-database have been rebuilt, we can remove the workaround that allowed to use old images
> ACS-8360 Remove workaround for old docker images

- tests/environment/alfresco-with-jolokia/Dockerfile
As per title, ref: https://github.com/Alfresco/alfresco-enterprise-repo/commit/6507a92f571d340a4cc43fa3caa294fc7a6df021
Failure on master: https://github.com/Alfresco/acs-packaging/actions/runs/10147799486/job/28059066955#step:8:605
> OPSEXP-2757 Fix AIMS tests after base Docker image bump

- .github/workflows/master_release.yml
As per title, waiting for https://github.com/Alfresco/alfresco-enterprise-share/actions/runs/10181534940/job/28163060119 to complete before merging.
> ACS-8490 [release] ACS 23.3.0-A31 [skip tests]

- .github/workflows/arm64.yml
- .github/workflows/ci.yml
- tests/pipeline-all-amps/repo/dtas/dtas-config.json
The ARM-powered GitHub hosted runners are finally available for Public Beta, meaning we don't need to create and destroy instances on EC2 to run this workflow anymore.
**Some test runs**:
- https://github.com/Alfresco/acs-packaging/actions/runs/10195150957
- https://github.com/Alfresco/acs-packaging/actions/runs/10195288805
> ACS-8490 Switch ARM64 workflow to GitHub hosted runners

- .github/workflows/arm64.yml
- .github/workflows/ci.yml
- .github/workflows/master_release.yml
- Migrate from `Node16` to `Node20`.
- Change `docker/setup-qemu-action` and `docker/login-action` to **v3**.
- Bump `actions/upload-artifact` to **v4**.
- Additionally: upgrading the version to the latest for other actions from the `alfresco-build-tools`.
> ACS-8670 Deal with upcoming GitHub Actions deprecations 

- .github/workflows/ci.yml
- .github/workflows/master_release.yml
- Migrate from `Node16` to `Node20`.
- Change `docker/setup-qemu-action` to **v3**.
- Additionally: upgrading the version to the latest for other actions from the `alfresco-build-tools`.
> ACS-8670 Deal with upcoming GitHub Actions deprecations

- .github/workflows/ci.yml
(cherry picked from commit 846a176bca5c3b99e7030a1bee430f810dc6c443)
> [ACS-9108] Bumped python version 3.7.15 -> 3.8.12 due to https://github.com/onnx/tensorflow-onnx/pull/2376 (#3014)

- tests/tas-distribution-zip/src/test/java/org/alfresco/distribution/CheckDistributionZipContents.java
As part of [MNT-24358], generate_keystores.bat and generate_keystores.sh were deleted because they were outdated config. Hence removing checks of both file from CheckDistributionZipContents.java which is leading to failure in CI.
[MNT-24358]: https://hyland.atlassian.net/browse/MNT-24358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MNT-24358] removing check of deleted files in test

- tests/tas-elasticsearch/pom.xml
Fixed dependencies related to elasticsearch-shared library changes. 
More information in ticket: https://hyland.atlassian.net/browse/ACS-9621
> ACS-9459 Bump ES Connector to 5.1.0-A.1
